from __future__ import annotations
import pandas as pd
import streamlit as st

def render_dynamic_chart(df: pd.DataFrame, cfg: dict | None) -> None:
    """
    Intelligently renders best-practice data visualizations based on 
    the dynamic JSON configuration payload generated by the LLM Planner.
    """
    if not cfg or cfg.get("chart_type") == "none":
        return

    chart_type = cfg.get("chart_type", "bar").lower()
    x_col = cfg.get("x")
    y_col = cfg.get("y")
    title = cfg.get("title", "Data Visualization")
    show_labels = cfg.get("show_labels", False)

    # Fallback validation: ensure requested columns exist in the DataFrame
    if x_col not in df.columns or y_col not in df.columns:
        st.caption("⚠️ *Visualization skipped: Expected query aliases do not match data schema.*")
        return

    st.write(f"📊 **{title}**")
    
    # Restructure dataframe for Streamlit high-value native rendering
    plot_df = df.set_index(x_col)[y_col]
    
    # Enforce maximum layout threshold to keep plots clean and scannable
    if len(plot_df) > 20:
        plot_df = plot_df.head(20)

    col, _ = st.columns([2, 1])
    with col:
        if chart_type == "line":
            st.line_chart(plot_df, use_container_width=True)
        elif chart_type == "area":
            st.area_chart(plot_df, use_container_width=True)
        elif chart_type == "pie":
            # Streamlit does not have a native st.pie_chart; use bar_chart with a pie tooltip caption fallback
            st.bar_chart(plot_df, use_container_width=True)
            st.caption("💡 *Pie structure mapped to clear comparison layout bars.*")
        else:
            st.bar_chart(plot_df, use_container_width=True)

    if show_labels:
        st.caption("💡 *Tip: Hover over the chart data points to view specific metric data label details.*")


def render_assistant_turn(msg: dict, *, df_key_suffix: str = "") -> None:
    """
    Guarantees consistent conversational UI rendering across historical replay and live streams.
    Follow-up routes and unserviceable requests bypass SQL or dataframe container cards completely.
    """
    # 1. Output Executive Business Summary Text First
    st.markdown(msg.get("content", ""))

    # Guardrail: Exit cleanly if this is a discussion or conversational follow-up
    if msg.get("is_followup"):
        return

    # 2. Render Compiled SQL Block expander if active
    if msg.get("sql"):
        with st.expander("🛠️ View Compiled Execution Query", expanded=False):
            st.code(msg["sql"], language="sql")

    # 3. Present Tabular Data Frame and trigger Dynamic Visualizer
    stored_df = msg.get("df")
    if stored_df is not None:
        df_obj = pd.DataFrame(stored_df) if isinstance(stored_df, list) else stored_df
        if not df_obj.empty:
            with st.expander("📋 View Result Data", expanded=False):
                st.dataframe(
                    df_obj,
                    use_container_width=True,
                    key=f"df_{df_key_suffix}" if df_key_suffix else None,
                )
            # Route to dynamic viz executor
            render_dynamic_chart(df_obj, msg.get("chart_cfg"))